require 'open-uri'
require 'net/http'
require 'json'
require 'pry'
require 'awesome_print'
require 'require_all'

# require_all './lib/'
require_relative './lib/cli.rb'
require_relative './lib/fetcher.rb'
require_relative './lib/player.rb'
require_relative './lib/team.rb'
require_relative './lib/menu.rb'
require_relative './lib/main_menu.rb'
require_relative './lib/player_menu.rb'
require_relative './lib/teams_menu.rb'
require_relative './lib/team_menu.rb'
require_relative './lib/players_list_menu.rb'