require 'open-uri'
require 'net/http'
require 'json'
require 'pry'
require 'awesome_print'

require_relative './lib/cli.rb'
require_relative './lib/fetcher.rb'
require_relative './lib/player.rb'
require_relative './lib/team.rb'